all: main.c avl.c elt.c
	gcc main.c avl.c elt.c -o main.exe
	echo "Le programme main.exe a été produit dans le répertoire programme1/"

clean:
	rm -rf main.exe

mrproper:
	echo "Suppression des fichiers output/"
	rm -rf output/*/*