all: main.c avl.c elt.c
	gcc main.c avl.c elt.c -o displayAVL.exe
	echo "Le programme displayAVL.exe a été produit dans le répertoire programme1/"

clean:
	rm -rf displayAVL.exe

mrproper:
	echo "Suppression des fichiers output/"
	rm -rf output/*/*